name: 记录成长

project:
    version: fong

license:
    software: MIT License
    software_url: http://opensource.org/licenses/MIT

links:
    header:
      - title: GitHub
        url: https://github.com/fongyk
    homepage:
      - title: LIVE & CHANGE
        url: https://fongyq.github.io/
    footer:
      - title: GitHub
        url: https://github.com/fongyk

ui:
  mode: 'auto' # 'auto', 'dark', 'light'
  brand:
    dark: "#00ceff"
    light: "#a20000"
  border_color:
    dark: "#5f5f5f"
    light: "#dee2e6"
  header:
    trianglify: true
    dark:
      color1: "#062a48"
      color2: "#304e67"
    light:
      color1: "#080331"
      color2: "#673051"
  masthead:
    color:
      dark: "#fff"
      light: "#fff"
    align:
      homepage: 'center'
      page: 'left'

social:
    github:
        enabled: false
        user: 
        repo: 
    twitter:
        enabled: false
        via:
        hash:
        account:
    facebook:
        enabled: false
        profileUrl:

analytics:
    google: UA-123456-1

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - jekyll-docs-theme.gemspec
  - LICENSE.md
  - README.md
  - screenshot.png
